In [1]:
import json
import sys
import os
sys.path.append('../..')
from downfolding_methods import norbs, fock_downfolding, Solve_fermionHam, JW_trans, Solve_qubitHam

In [2]:

def calc_FCI(fock_method,original_basis,folded_basis,name):
    # Set molecule parameters.
    bond_length_interval = 0.1
    n_points = 25

    # Generate molecule at different bond lengths.
    bond_lengths = []
    name_energies = []
    for point in range(3, n_points + 1):
        bond_length = bond_length_interval * point
        bond_lengths += [bond_length]
        geometry = 'H 0 0 0; H 0 0 '+str(bond_length)
        print(geometry)
        n_folded = norbs(atom=geometry,basis = folded_basis)
        ham = fock_downfolding(n_folded=n_folded,fock_method=fock_method,QO=True,atom=geometry,basis = original_basis)
        E = Solve_fermionHam(ham.Ham_const,ham.int_1bd.real,ham.int_2bd.real,nele=2,method='FCI')
        name_energies.append(E)
        print('bond length',bond_length)
    if os.path.isfile('res/res_FCI_QO.json'):
        res = open('res/res_FCI_QO.json')
        res = json.load(res)
    else:
        res = {}
    if 'bond_lengths' not in res:
        res['bond_lengths'] = bond_lengths
    res[name] = name_energies
    with open('res/res_FCI_QO.json','w') as data_file:
        json.dump(res,data_file)


In [3]:
#calc_FCI('HF','sto-3G','sto-3G','sto-3Gs')
calc_FCI('HF','ccpVDZ','sto-3G','HFpVDZs')
calc_FCI('lda,vwn','ccpVDZ','sto-3G','KSpVDZs')
calc_FCI('EGNN','ccpVDZ','sto-3G','EGNNpVDZs')
#calc_FCI('HF','ccpVDZ','ccpVDZ','fci_energies')

H 0 0 0; H 0 0 0.30000000000000004
energy2: [-1.88973876e+00 -1.88973876e+00 -1.77435977e+00 -9.60102966e-01
 -1.79323514e-01 -1.10261239e-01 -1.10261239e-01 -1.65177630e-02
 -5.84501504e-03 -2.92007954e-15]
bond length 0.30000000000000004
H 0 0 0; H 0 0 0.4


Overwritten attributes  get_hcore get_ovlp  of <class 'pyscf.scf.hf.RHF'>


energy2: [-1.81245632e+00 -1.81245632e+00 -1.63309231e+00 -9.39441679e-01
 -2.83127195e-01 -1.87543683e-01 -1.87543683e-01 -2.77884736e-02
 -8.91444893e-03 -1.97086205e-14]
bond length 0.4
H 0 0 0; H 0 0 0.5
energy2: [-1.72287388e+00 -1.72287388e+00 -1.48815793e+00 -9.67845627e-01
 -3.68714698e-01 -2.77126123e-01 -2.77126123e-01 -4.07850563e-02
 -1.29937803e-02 -2.02177584e-14]
bond length 0.5
H 0 0 0; H 0 0 0.6000000000000001
energy2: [-1.62668607e+00 -1.62668607e+00 -1.35652420e+00 -1.04812629e+00
 -4.15358073e-01 -3.73313926e-01 -3.73313926e-01 -5.48225620e-02
 -2.02822448e-02  1.31830276e-14]
bond length 0.6000000000000001
H 0 0 0; H 0 0 0.7000000000000001
energy2: [-1.52937394e+00 -1.52937394e+00 -1.25004737e+00 -1.15552698e+00
 -4.70626058e-01 -4.70626058e-01 -4.28436220e-01 -6.93304312e-02
 -3.46761862e-02  2.65250427e-15]
bond length 0.7000000000000001
H 0 0 0; H 0 0 0.8
energy2: [-1.43571256e+00 -1.43571256e+00 -1.25804886e+00 -1.17395716e+00
 -5.64287441e-01 -5.64287441e-01 -

/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/cuda/__init__.py:118: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type an

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']


/home/hewenhao/Documents/wenhaohe/research/VQE_downfold/pkgs/dataframe.py:203: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:274.)
  pos = torch.tensor(data['coordinates'])[ind_list].to(device);


dbg2: [-1.25453452 -0.16316426 -0.01786003  1.00236906  1.05139685  1.05139685
  1.82129974  1.82129974  2.0678033   7.84970421]
energy2: [-1.88973876e+00 -1.88973876e+00 -1.77435977e+00 -9.75168395e-01
 -1.70345668e-01 -1.10261239e-01 -1.10261239e-01 -1.65177630e-02
 -5.84501504e-03 -5.78946339e-15]
bond length 0.30000000000000004
H 0 0 0; H 0 0 0.4


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-1.19019161 -0.14740452  0.01804784  0.91743385  1.05197925  1.05197925
  1.79048884  1.79048884  2.05723783  6.5802836 ]
energy2: [-1.81245632e+00 -1.81245632e+00 -1.63309231e+00 -9.67707047e-01
 -2.64888979e-01 -1.87543683e-01 -1.87543683e-01 -2.77884736e-02
 -8.91444893e-03 -2.23695264e-14]
bond length 0.4
H 0 0 0; H 0 0 0.5


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-1.12662091 -0.13387209  0.05627938  0.83182955  1.0525345   1.0525345
  1.75207956  1.75207956  2.03231349  5.42936515]
energy2: [-1.72287388e+00 -1.72287388e+00 -1.48815793e+00 -9.97391860e-01
 -3.47843621e-01 -2.77126123e-01 -2.77126123e-01 -4.07850563e-02
 -1.29937803e-02 -2.73980848e-14]
bond length 0.5
H 0 0 0; H 0 0 0.6000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-1.0457142  -0.14050973  0.08441689  0.73931819  0.99512317  0.99512317
  1.72792857  1.72792857  1.85821905  4.32174246]
energy2: [-1.62668607e+00 -1.62668607e+00 -1.35652420e+00 -1.05527552e+00
 -4.19703740e-01 -3.73313926e-01 -3.73313926e-01 -5.48225620e-02
 -2.02822448e-02  1.39410540e-14]
bond length 0.6000000000000001
H 0 0 0; H 0 0 0.7000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.9918487  -0.14148197  0.12352269  0.67226902  0.98285355  0.98285355
  1.69693535  1.69693535  1.76188066  3.43538931]
energy2: [-1.52937394e+00 -1.52937394e+00 -1.25004737e+00 -1.15632844e+00
 -4.70626058e-01 -4.70626058e-01 -4.39561973e-01 -6.93304312e-02
 -3.46761862e-02  1.35526690e-15]
bond length 0.7000000000000001
H 0 0 0; H 0 0 0.8


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.94021259 -0.1484235   0.1592622   0.61988462  0.97586154  0.97586154
  1.65145781  1.66421913  1.66421913  2.88520459]
energy2: [-1.43571256e+00 -1.43571256e+00 -1.25723980e+00 -1.17395716e+00
 -5.64287441e-01 -5.64287441e-01 -4.39173773e-01 -8.39099910e-02
 -6.11601194e-02 -5.50916256e-15]
bond length 0.8
H 0 0 0; H 0 0 0.9


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.89077826 -0.16012011  0.1918991   0.5787243   0.97625445  0.97625445
  1.53341815  1.62767036  1.62767036  2.57760407]
energy2: [-1.34943194e+00 -1.34943194e+00 -1.33435394e+00 -1.12753700e+00
 -6.50568060e-01 -6.50568060e-01 -4.30000380e-01 -1.04338349e-01
 -9.82069382e-02 -9.27129144e-15]
bond length 0.9
H 0 0 0; H 0 0 1.0


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.84621045 -0.17193925  0.22538007  0.54392088  0.98605003  0.98605003
  1.41559719  1.58600722  1.58600722  2.3962694 ]
energy2: [-1.37793873e+00 -1.27305499e+00 -1.27305499e+00 -1.10632757e+00
 -7.26945007e-01 -7.26945007e-01 -4.15935511e-01 -1.66088461e-01
 -1.12356761e-01  1.17440714e-16]
bond length 1.0
H 0 0 0; H 0 0 1.1


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.80760323 -0.18150736  0.26134348  0.51276925  1.00510935  1.00510935
  1.30521465  1.54009937  1.54009937  2.27139216]
energy2: [-1.38767571e+00 -1.20790391e+00 -1.20790391e+00 -1.10448842e+00
 -7.92096094e-01 -7.92096094e-01 -3.99990586e-01 -2.45446423e-01
 -1.26021171e-01  5.17689724e-15]
bond length 1.1
H 0 0 0; H 0 0 1.2000000000000002


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.77407165 -0.18933552  0.29859845  0.48587934  1.0313504   1.0313504
  1.20793327  1.49248645  1.49248645  2.16839621]
energy2: [-1.36888628e+00 -1.15424112e+00 -1.15424112e+00 -1.11639555e+00
 -8.45758878e-01 -8.45758878e-01 -3.84878062e-01 -3.38084819e-01
 -1.39149813e-01  6.25329773e-15]
bond length 1.2000000000000002
H 0 0 0; H 0 0 1.3


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.74432823 -0.19658353  0.33526206  0.46440703  1.06195068  1.06195068
  1.12782829  1.44620656  1.44620656  2.07190775]
energy2: [-1.32996752e+00 -1.13737731e+00 -1.11149688e+00 -1.11149688e+00
 -8.88503122e-01 -8.88503122e-01 -4.37859705e-01 -3.71968915e-01
 -1.51626191e-01 -6.86060560e-15]
bond length 1.3
H 0 0 0; H 0 0 1.4000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.71745132 -0.20413449  0.36965298  0.44891484  1.06781008  1.0941314
  1.0941314   1.40403685  1.40403685  1.9764749 ]
energy2: [-1.27999282e+00 -1.16389876e+00 -1.07853265e+00 -1.07853265e+00
 -9.21467352e-01 -9.21467352e-01 -5.38191072e-01 -3.61611303e-01
 -1.63344524e-01  2.44890735e-16]
bond length 1.4000000000000001
H 0 0 0; H 0 0 1.5


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.69300616 -0.21239044  0.40025866  0.43927219  1.02987238  1.12559598
  1.12559598  1.36795851  1.36795851  1.88153708]
energy2: [-1.22689074e+00 -1.19349408e+00 -1.05389677e+00 -1.05389677e+00
 -9.46103225e-01 -9.46103225e-01 -6.33234726e-01 -3.53718989e-01
 -1.74233160e-01 -4.33374164e-16]
bond length 1.5
H 0 0 0; H 0 0 1.6


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.6708643  -0.22127768  0.42551206  0.43471113  1.01478113  1.15467548
  1.15467548  1.33885331  1.33885331  1.78875952]
energy2: [-1.22460667e+00 -1.17648024e+00 -1.03604129e+00 -1.03604129e+00
 -9.63958711e-01 -9.63958711e-01 -7.18579927e-01 -3.48123088e-01
 -1.84267103e-01  3.16799123e-15]
bond length 1.6
H 0 0 0; H 0 0 1.7000000000000002


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.6509663  -0.23043014  0.4340837   0.44404581  1.02124627  1.18026999
  1.18026999  1.31654108  1.31654108  1.70063903]
energy2: [-1.25638169e+00 -1.13228213e+00 -1.02348350e+00 -1.02348350e+00
 -9.76516498e-01 -9.76516498e-01 -7.91497591e-01 -3.44669181e-01
 -1.93467997e-01  7.10133103e-17]
bond length 1.7000000000000002
H 0 0 0; H 0 0 1.8


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.63318379 -0.23942703  0.43621697  0.45538932  1.04525868  1.20172885
  1.20172885  1.30009145  1.30009145  1.61972806]
energy2: [-1.28841014e+00 -1.09584182e+00 -1.01490906e+00 -1.01490906e+00
 -9.85090935e-01 -9.85090935e-01 -8.50883076e-01 -3.43170345e-01
 -2.01894591e-01  8.58384461e-15]
bond length 1.8
H 0 0 0; H 0 0 1.9000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.6172927  -0.24794288  0.44014521  0.46025084  1.08058954  1.2187727
  1.2187727   1.28823727  1.28823727  1.54811743]
energy2: [-1.32045331e+00 -1.06727720e+00 -1.00922280e+00 -1.00922280e+00
 -9.90777197e-01 -9.90777197e-01 -8.97028761e-01 -3.43340936e-01
 -2.09628760e-01 -3.16357346e-15]
bond length 1.9000000000000001
H 0 0 0; H 0 0 2.0


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.60658852 -0.26058606  0.44365827  0.45755076  1.11462979  1.22563305
  1.22563305  1.27389801  1.27389801  1.48148289]
energy2: [-1.35223407e+00 -1.04590699e+00 -1.00555905e+00 -1.00555905e+00
 -9.94440951e-01 -9.94440951e-01 -9.31284185e-01 -3.45294126e-01
 -2.16761820e-01  1.20683373e-15]
bond length 2.0
H 0 0 0; H 0 0 2.1


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.59359019 -0.26777173  0.44952782  0.45399765  1.15295072  1.2349103
  1.2349103   1.26807462  1.26807462  1.43097828]
energy2: [-1.38337128e+00 -1.03042763e+00 -1.00326485e+00 -1.00326485e+00
 -9.96735151e-01 -9.96735151e-01 -9.55630469e-01 -3.47314439e-01
 -2.23384094e-01 -2.76063386e-15]
bond length 2.1
H 0 0 0; H 0 0 2.2


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.58168136 -0.27432237  0.44859209  0.45605458  1.18579077  1.24181785
  1.24181785  1.26444333  1.26444333  1.39018914]
energy2: [-1.41343660e+00 -1.01962823e+00 -1.00186832e+00 -1.00186832e+00
 -9.98131683e-01 -9.98131683e-01 -9.72245250e-01 -3.49690325e-01
 -2.29578588e-01 -2.59593100e-15]
bond length 2.2
H 0 0 0; H 0 0 2.3000000000000003


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.57075003 -0.28029793  0.44234213  0.4629594   1.21170777  1.24696037
  1.24696037  1.26242983  1.26242983  1.35810096]
energy2: [-1.44204383e+00 -1.01233618e+00 -1.00104175e+00 -1.00104175e+00
 -9.98958251e-01 -9.98958251e-01 -9.83163539e-01 -3.52045066e-01
 -2.35418045e-01  3.07975279e-15]
bond length 2.3000000000000003
H 0 0 0; H 0 0 2.4000000000000004


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.56069764 -0.28575572  0.43594968  0.46993957  1.23081866  1.25084314
  1.25084314  1.26156456  1.26156456  1.33346061]
energy2: [-1.46890392e+00 -1.00756052e+00 -1.00056598e+00 -1.00056598e+00
 -9.99434020e-01 -9.99434020e-01 -9.90088504e-01 -3.54083204e-01
 -2.40963935e-01  4.11660974e-15]
bond length 2.4000000000000004
H 0 0 0; H 0 0 2.5


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.55143762 -0.290748    0.42988408  0.47667796  1.24411958  1.25386033
  1.25386033  1.26148533  1.26148533  1.3149625 ]
energy2: [-1.49383614e+00 -1.00452148e+00 -1.00029961e+00 -1.00029961e+00
 -9.99700385e-01 -9.99700385e-01 -9.94334763e-01 -3.55604105e-01
 -2.46266151e-01 -2.62429795e-15]
bond length 2.5
