In [1]:
import json
import sys
import os
sys.path.append('../..')
from downfolding_methods import norbs, fock_downfolding, Solve_fermionHam, JW_trans, Solve_qubitHam

In [2]:

def calc_FCI(fock_method,original_basis,folded_basis,name):
    # Set molecule parameters.
    bond_length_interval = 0.1
    n_points = 25

    # Generate molecule at different bond lengths.
    bond_lengths = []
    name_energies = []
    for point in range(3, n_points + 1):
        bond_length = bond_length_interval * point
        bond_lengths += [bond_length]
        geometry = 'H 0 0 0; H 0 0 '+str(bond_length)
        n_folded = norbs(atom=geometry,basis = folded_basis)
        ham = fock_downfolding(n_folded=n_folded,fock_method=fock_method,QO=False,atom=geometry,basis = original_basis)
        E = Solve_fermionHam(ham.Ham_const,ham.int_1bd,ham.int_2bd,nele=2,method='FCI')
        name_energies.append(E)
        print('bond length',bond_length)
    if os.path.isfile('res/res_FCI.json'):
        res = open('res/res_FCI.json')
        res = json.load(res)
    else:
        res = {}
    if 'bond_lengths' not in res:
        res['bond_lengths'] = bond_lengths
    res[name] = name_energies
    with open('res/res_FCI.json','w') as data_file:
        json.dump(res,data_file)

        
def calc_ED(fock_method,original_basis,folded_basis,name):
    # Set molecule parameters.
    bond_length_interval = 0.1
    n_points = 25

    # Generate molecule at different bond lengths.
    bond_lengths = []
    name_energies = []
    for point in range(3, n_points + 1):
        bond_length = bond_length_interval * point
        bond_lengths += [bond_length]
        geometry = 'H 0 0 0; H 0 0 '+str(bond_length)
        n_folded = norbs(atom=geometry,basis = folded_basis)
        ham = fock_downfolding(n_folded=n_folded,fock_method=fock_method,QO=False,atom=geometry,basis = original_basis)
        q_ham = JW_trans(ham.Ham_const,ham.int_1bd,ham.int_2bd)
        E = Solve_qubitHam(q_ham,method='ED')
        name_energies.append(E)
        print('bond length',bond_length)
    if os.path.isfile('res/res_ED.json'):
        res = open('res/res_ED.json')
        res = json.load(res)
    else:
        res = {}
    if 'bond_lengths' not in res:
        res['bond_lengths'] = bond_lengths
    res[name] = name_energies
    with open('res/res_ED.json','w') as data_file:
        json.dump(res,data_file)

In [3]:
calc_FCI('HF','sto-3G','sto-3G','sto-3Gs')
calc_FCI('HF','ccpVDZ','sto-3G','HFpVDZs')
calc_FCI('lda,vwn','ccpVDZ','sto-3G','KSpVDZs')
calc_FCI('EGNN','ccpVDZ','sto-3G','EGNNpVDZs')
calc_FCI('HF','ccpVDZ','ccpVDZ','fci_energies')

/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/cuda/__init__.py:118: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type an

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']


/home/hewenhao/Documents/wenhaohe/research/VQE_downfold/pkgs/dataframe.py:203: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:274.)
  pos = torch.tensor(data['coordinates'])[ind_list].to(device);


dbg2: [-1.25453452 -0.16316426 -0.01786003  1.00236906  1.05139685  1.05139685
  1.82129974  1.82129974  2.0678033   7.84970421]
bond length 0.30000000000000004


Overwritten attributes  get_ovlp get_hcore  of <class 'pyscf.scf.hf.RHF'>
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation 

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-1.19019161 -0.14740452  0.01804784  0.91743385  1.05197925  1.05197925
  1.79048884  1.79048884  2.05723783  6.5802836 ]
bond length 0.4


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-1.12662091 -0.13387209  0.05627938  0.83182955  1.0525345   1.0525345
  1.75207956  1.75207956  2.03231349  5.42936515]
bond length 0.5


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-1.0457142  -0.14050973  0.08441689  0.73931819  0.99512317  0.99512317
  1.72792857  1.72792857  1.85821905  4.32174246]
bond length 0.6000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.9918487  -0.14148197  0.12352269  0.67226902  0.98285355  0.98285355
  1.69693535  1.69693535  1.76188066  3.43538931]
bond length 0.7000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.94021259 -0.1484235   0.1592622   0.61988462  0.97586154  0.97586154
  1.65145781  1.66421913  1.66421913  2.88520459]
bond length 0.8


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.89077826 -0.16012011  0.1918991   0.5787243   0.97625445  0.97625445
  1.53341815  1.62767036  1.62767036  2.57760407]
bond length 0.9


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.84621045 -0.17193925  0.22538007  0.54392088  0.98605003  0.98605003
  1.41559719  1.58600722  1.58600722  2.3962694 ]
bond length 1.0


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.80760323 -0.18150736  0.26134348  0.51276925  1.00510935  1.00510935
  1.30521465  1.54009937  1.54009937  2.27139216]
bond length 1.1


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.77407165 -0.18933552  0.29859845  0.48587934  1.0313504   1.0313504
  1.20793327  1.49248645  1.49248645  2.16839621]
bond length 1.2000000000000002


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.74432823 -0.19658353  0.33526206  0.46440703  1.06195068  1.06195068
  1.12782829  1.44620656  1.44620656  2.07190775]
bond length 1.3


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.71745132 -0.20413449  0.36965298  0.44891484  1.06781008  1.0941314
  1.0941314   1.40403685  1.40403685  1.9764749 ]
bond length 1.4000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.69300616 -0.21239044  0.40025866  0.43927219  1.02987238  1.12559598
  1.12559598  1.36795851  1.36795851  1.88153708]
bond length 1.5


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.6708643  -0.22127768  0.42551206  0.43471113  1.01478113  1.15467548
  1.15467548  1.33885331  1.33885331  1.78875952]
bond length 1.6


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.6509663  -0.23043014  0.4340837   0.44404581  1.02124627  1.18026999
  1.18026999  1.31654108  1.31654108  1.70063903]
bond length 1.7000000000000002


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.63318379 -0.23942703  0.43621697  0.45538932  1.04525868  1.20172885
  1.20172885  1.30009145  1.30009145  1.61972806]
bond length 1.8


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.6172927  -0.24794288  0.44014521  0.46025084  1.08058954  1.2187727
  1.2187727   1.28823727  1.28823727  1.54811743]
bond length 1.9000000000000001


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.60658852 -0.26058606  0.44365827  0.45755076  1.11462979  1.22563305
  1.22563305  1.27389801  1.27389801  1.48148289]
bond length 2.0


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.59359019 -0.26777173  0.44952782  0.45399765  1.15295072  1.2349103
  1.2349103   1.26807462  1.26807462  1.43097828]
bond length 2.1


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.58168136 -0.27432237  0.44859209  0.45605458  1.18579077  1.24181785
  1.24181785  1.26444333  1.26444333  1.39018914]
bond length 2.2


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.57075003 -0.28029793  0.44234213  0.4629594   1.21170777  1.24696037
  1.24696037  1.26242983  1.26242983  1.35810096]
bond length 2.3000000000000003


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.56069764 -0.28575572  0.43594968  0.46993957  1.23081866  1.25084314
  1.25084314  1.26156456  1.26156456  1.33346061]
bond length 2.4000000000000004


/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn(
/home/hewenhao/anaconda3/envs/ML_DFT/lib/python3.8/site-packages/torch/jit/_check.py:177: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warning

Solving 0th molecule: H2
perm_mat: [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
new inds: [0 1 4 2 3 5 6 9 7 8]
verify perm_mat: ['0 H 1s    ', '0 H 2s    ', '0 H 2pz   ', '0 H 2px   ', '0 H 2py   ', '1 H 1s    ', '1 H 2s    ', '1 H 2pz   ', '1 H 2px   ', '1 H 2py   ']
dbg2: [-0.55143762 -0.290748    0.42988408  0.47667796  1.24411958  1.25386033
  1.25386033  1.26148533  1.26148533  1.3149625 ]
bond length 2.5
